### PR TITLE
Add Translation Context

### PR DESCRIPTION
**Pull request by komape**
@HighLiuk opened #25 as @jakobaltendorfer added support for tranalsation context in thier fork. This PR adds these changes.

### CODE REVIEW

**Comment by komape** [comment]
@jakobaltendorfer Do you want your fork be merged into this repo?

**Comment by jakobaltendorfer** [comment]
Yes, you can merge my fork if that's fine with you.

**Comment by komape** [comment]
@jakobaltendorfer I would like to but I want to make sure it works correctly. Do you have some tests?

**Comment by jakobaltendorfer** [comment]
@komape I haven't written tests for this yet, but I can add them.

**Comment by jakobaltendorfer** [comment]
@komape can you take a look at it?

**Comment by komape** [comment]
> can you take a look at it?

Will do soon. Thanks for the work!

**Comment by komape** [comment]
The tests failed due to missing access of the PR to the repository's secrets. Tested locally and they suceed.

@jakobaltendorfer Thanks for the contribution. I will merge it and publish the changes.

**Pull request merged**
